### PR TITLE
ggcorr: improvements + vignette

### PR DESCRIPTION
**Pull request by briatte**
see https://briatte.github.io/ggcorr/

### CODE REVIEW

**Comment by schloerke** [comment]
Very nice vignette!!! Do you know of a way we can link it directly from the package? 
* I'd really like for it to show up as a vignette in R, but I also understand the ease of use with the website/markdown.  
* Is there a "url" field for a function? I'd be happy with that.
* I know you were worried about large graphics which makes for large vignettes, but the visual output is "small" for a display, so I'm not too worried if they are included internally.

Thoughts?

**Comment by briatte** [comment]
Thanks for the feedback.

> Is there a "url" field for a function? I'd be happy with that.

I don't think there is such a field.

> Do you know of a way we can link it directly from the package?

The CRAN pages can show one URL per package. One possibility is to use that URL to create an index page for `GGally`, which would include links to all vignettes and to the GitHub repo.

All it would take is a simple HTML page like this one:

> http://f.briatte.org/temp/ggally_index.html

**Comment by schloerke** [comment]
Perfect!  I prefer simple.

Hopefully I'll be able to make a vignette for ggpairs and ggmatrix this weekend.

Can you make a PR to the gh-pages branch with the homepage and your ggcorr vignette output (and original vignette)?

**Comment by briatte** [comment]
- [PR](https://github.com/ggobi/ggally/pull/98) with homepage styled like the vignettes
- [PR](https://github.com/ggobi/ggally/pull/99) to mention the homepage in DESCRIPTION

I'll add the actual vignettes later on, when the package gets closer to published status. Right now, I use the standalone versions of `ggcorr` and `ggnet2` to produce the vignettes.

**Pull request merged**
