### PR TITLE
Updates to ggnet, ggnet2 and ggnetworkmap

### PR DESCRIPTION
**Pull request by briatte**
This PR harmonizes the code of all network plotting functions in the package to work with `igraph` while not depending on it.

- `DESCRIPTION`
  - anticipate on `gh-pages` by adding the homepage URL
  - mention `ggnet2` in authors attributions
  - slightly improve package description
  - ~~removed `igraph` from `Suggests`~~
- `ggnet` and `ggnet2`
  - avoid potential namespace conflict with `igraph`
- `ggnetworkmap`
  - removed dependency to `igraph`
  - slightly improved the code
  - slightly improved coverage tests
  - slightly improved the vignette

Comments on `ggnetworkmap` for @elbamos

- I must say that I find the code of `ggnetworkmap` quite difficult to follow at times, even though I really like the functionality that it provides. I have tried to rewrite some parts to add some of the functionalities of the updated `ggnet` function.
- Some of the examples for `ggnetworkmap` provided do not return anything meaningful, e.g. the "domestic distribution" plot shows nothing. Also, the arrows do not seem to show up where they should on some of the last examples.
- Would it be possible to tweak the US airports examples to show connections only in the US? The plot produced by the example currently shows ties that go outside of the US, with no map beneath it.
- I am further unsure of the illustrative quality of the `twitter_spambots` data (formerly `twitter_spam_community`). First, plotting worldwide maps with `ggplot2` is partially broken because of weird polygon issues near both poles (there's a horizontal line across Siberia), and the network does not span worldwide, it's almost entirely US-based. See also suggestion below.
- I wonder whether the `net` argument (formerly `data`) should really come first int he function call if it can be ignored, which is not the case of `net`, the second argument.
- The vignette should indicate that there is a really cool network+maps package in development, `spnet`: http://cran.at.r-project.org/web/packages/spnet/

If `ggnetworkmap` needs an example of a dense network, perhaps the data in [this folder](https://github.com/briatte/ggnet/tree/master/data) could be of some use. It shows the follower-followee ties between French MPs a few years ago. Each MP comes from a constituency that can be geocoded. This would allow showing how `ggnetworkmap` performs on dense networks with some overplotting. The data also serve to illustrate `ggnet` and `ggnet2`, as shown in the [vignette for `ggnet2`](https://briatte.github.io/ggnet/#example-4-french-mps-on-twitter).

I have left the vignette inside the package, but ultimately it should move to `gh-pages` with the other ones, if we stick to the plan envisioned in #97 with @schloerke.

### CODE REVIEW

**Comment by elbamos** [comment]
Can you clarify some of what the proposed changes are?  It looks like compatibility with igraph was taken out, there was some minor refactoring (i.e., changing “expect_equal” to “expect_equivalent” and the like) but I don’t see any new functionality or broadened coverage?  (Perhaps the coverage % change is because the length of the code changed…)

I will take another look at the two examples.  They certainly work for me, and they illustrate the functionality this provides that ggnet didn’t — flexibility in terms of the presentation, and overlaying on a map.  So I’m not sure what you’re seeing.  But some of the dependencies have gone through several iterations since I submitted this PR in January.  

Net comes second in the function to facilitate pipelining.  

Also - don’t mean to make a big deal out of this, but why did you change the author attributions?  I don’t think there’s any ggnet code left in this.

**Comment by elbamos** [comment]
What’s timing at this point?  How soon do I need to get in changes to hit the next release?

From: Amos B. Elberg <amos.elberg@me.com>
Reply: Amos B. Elberg <amos.elberg@me.com>
Date: September 12, 2015 at 5:32:26 PM
To: François Briatte <notifications@github.com>, ggobi/ggally <ggally@noreply.github.com>, ggobi/ggally <reply@reply.github.com>
Subject:  Re: [ggally] updates to DESCRIPTION and ggnetworkmap (#100)  

Can you clarify some of what the proposed changes are?  It looks like compatibility with igraph was taken out, there was some minor refactoring (i.e., changing “expect_equal” to “expect_equivalent” and the like) but I don’t see any new functionality or broadened coverage?  (Perhaps the coverage % change is because the length of the code changed…)

I will take another look at the two examples.  They certainly work for me, and they illustrate the functionality this provides that ggnet didn’t — flexibility in terms of the presentation, and overlaying on a map.  So I’m not sure what you’re seeing.  But some of the dependencies have gone through several iterations since I submitted this PR in January.  

Net comes second in the function to facilitate pipelining.  

Also - don’t mean to make a big deal out of this, but why did you change the author attributions?  I don’t think there’s any ggnet code left in this.

**Comment by briatte** [comment]
Hi @elbamos,

> Can you clarify some of what the proposed changes are?

It's mostly refactoring, and additional checks on the kind of object that the function allows. In its current state, the function accepts anything that can be coerced to a `network` object, and refuses to plot hyper-graphs or multiplex graphs, which return an error when you try to get their edge list.

One thing that I have not yet looked at in detail has to do with how attributes are passed to arguments like `ring.group`. I'd like to suggest the same flexibility than for `ggnet` and `ggnet2`, where you can pass a single value, a vector of values or a network attribute to the argument.

> Also - don’t mean to make a big deal out of this, but why did you change the author attributions?  I don’t think there’s any ggnet code left in this.  

Which attribution are you referring to? I've added `ggnet2` to the DESCRIPTION file and added you as the author of `twitter_spambots`. The author line of `ggnetworkmap` is [unchanged](https://github.com/ggobi/ggally/pull/100/files#diff-bed0e86cdf401b4bd4d69d1f4f20250bR41). I did remove the author/date headings from the vignette, though—in order to style all vignettes similarly before inclusion in the `gh-pages` branch. I don't have any objections to keeping an author/date mention in the vignettes if that's more appropriate.

**Comment by schloerke** [comment]
Questions @briatte:
* With all the igraph code being removed, if I submit an ```igraph``` object and it will convert it to a ```sna``` object, and everything will continue as expected?
* Is The motivation behind this is to make internal code consistent? or to remove igraph so the tests pass?


Decisions:
* I'd like to keep the author and date on the vignettes.  It's nice to know when they were last updated and who 'owns' the function

Timeline:
@elbamos, When would work for you?  I'd like to get this out sooner rather than later.  I still need a week to finish up some last issues on my end. (and make a vignette for ggpairs)

**Comment by elbamos** [comment]
Thanks Barret. If I don't get to it by tomorrow night I will do so by Monday (weekend guest...). I've been trying to wrap up a major PR integrating  R into the Apache-Zeppelin project and that's been consuming time.

Regarding igraph I'm likely to put the dependency back in. The reason has to do with a namespace conflict between igraph and network. If you load them in the wrong order and then try to convert an igraph for charting, you can get an error that takes a long time to track down. So I wanted to handle that in code. The other reason is that once igraph gets pushed with some changes I'd proposed, using igraph will enable some expanded functionality regarding categorical variables.

That said, I like a lot of the code changes folks proposed, and many of the constructive comments are well-taken, appreciated, and things I'd like to try to address.

**Comment by briatte** [comment]
@schloerke 

> With all the `igraph` code being removed, if I submit an `igraph` object and it will convert it to a `sna` object, and everything will continue as expected?

Yes: as long as the `intergraph` package is installed, any `igraph` one-mode network will be converted to a `network` object prior to plotting. If the package is not installed, the user gets offered to install it.

> Is The motivation behind this is to make internal code consistent? or to remove igraph so the tests pass?

It's a matter of both. The basic issue is that loading both `network` and `igraph` is tricky due to the namespace issues that @elbamos is referring to. An example is shown in PR #94.

The three options are

1. use only `network` and `sna`
2. use `network`, `sna` and `igraph` altogether
3. use only `igraph`

So far, I've been trying to implement option (1). Option (2) is risky. Option (3) is a possibility, although it would require rewriting a lot of the code, and would almost certainly break old code.

**Comment by elbamos** [comment]
I don't think that's right. There's a namespace collision between igraph and network. Unless you load in a particular order conversion will fail with an error that it can't find one of the functions in the intergraph package.

**Comment by briatte** [comment]
@elbamos That's new to me. Do you have a minimal reprex, please? I was relying on `intergraph` precisely to avoid that issue.

The following examples work fine on my end:

```r
library(network)
library(igraph)
library(intergraph)

# network -> igraph
n = network(sna::rgraph(10))
asIgraph(n)

# igraph -> network
n = random.graph.game(5, .5)
asNetwork(n)

## restarting R...

library(igraph)
library(network)
library(intergraph)

# network -> igraph
n = network(sna::rgraph(10))
asIgraph(n)

# igraph -> network
n = random.graph.game(5, .5)
asNetwork(n)
```

**Comment by elbamos** [comment]
I don't - the  last time I looked at any or this stuff was when I wrote the code 7 months ago. I can take a try tonight, but did you try starting a fresh session and loading igraph first?

If the issue has been fixed then great and that's a different story, but I had all sorts of issues with this way back, which was a driver for the way I wrote the code.

**Comment by briatte** [comment]
Code block (2) in the Gist I linked to loads `igraph` before `network`. This does not seem to create any issue with `intergraph`, which has been stable for some time (the [recent updates](https://github.com/mbojan/intergraph/commits/master) only add a few little things for compatibility with `igraph` 1.0.0).

**Comment by briatte** [comment]
Following the discussion here and in #94, I've reintegrated `igraph` to the `Suggests`. The package should now always work with `igraph` while not depending on it.

**Comment by schloerke** [comment]
@briatte Thanks!

@elbamos The merge looks good to me. I've made a public branch of "briatte_dev_PR100".  This should make it much easier for you if you want to make changes.  Let me know how/if I can help.

**Comment by elbamos** [comment]
Ok ok - I’m not going to be able to look at this for a few days, and since you guys seem pretty positive, I’m not going to hold-up the train.

**Comment by schloerke** [comment]
Ok, I'm going to merge this into dev branch.  

@elbamos, feel free to make corrections with another PR to dev. :-)

**Comment by mbojan** [comment]
Just to drop two cents as I ate my teeth on the igraph/network namespace conflicts while working on intergaph. Please let me know if you find cases where `intergraph` does not work as expected

In the long run I would suggest avoiding putting neither igraph nor network (nor any other network-data-object-implementing packages that you might consider adding in the future) to `Suggests` etc. Stick to `Imports` and use `::`. Even though there is a typing overhead.

Another possibility to consider is to use `import` package https://github.com/smbache/import It was not around when I wrote the core of intergraph.

**Comment by schloerke** [comment]
Hi @mbojan,

Motivation behind ```Suggests``` is to not force a user to download the network packages if they do not need the network based functions.

I've never seen the ```import``` package.  This looks very promising if we run into any more issues. Thank you!

**Comment by briatte** [comment]
@mbojan Thanks for the input. I have not encountered a situation where `intergraph` fails due to a namespace conflict between `igraph` and `network`. The only thing that I would like to see added to the package one day is support for bipartite graphs (although I have no idea how `igraph` handles these).

Re: cleaning up the `Suggests` field, won't CRAN hate us if we use `pkg::function` without declaring `pkg` in the `Suggests`?

Re: `import` package, it does seem very promising. The README indicates that when used within a package, it uses the namespace of that package. That might just work.

**Comment by schloerke** [comment]
@elbamos, I believe the rule is "If it is in Suggests, it must be used like ```pkg::function```.  Using ```pkg::function``` does not force it to be a Suggests package."

Sp, I could do 
```{r}
str_c <- function(...) {
  stringr::str_c(..., sep = " not a space ")
}
```
where stringr is imported.

**Comment by mbojan** [comment]
@briatte 
> Re: cleaning up the Suggests field, won't CRAN hate us if we use pkg::function without declaring pkg in the Suggests?

It did not hate me for `intergraph` which does just that.... ;-) But seriously speaking, they do not have to be, as stated by the `R-exts` manual (https://cran.rstudio.com/doc/manuals/r-release/R-exts.html#Package-Dependencies, paragraph 6). As @schloerke suggested meanwhile.

> bipartite graphs

They kind-of work but I blocked it because I decided that "kind-of" is not enough. They are also handled differently in `igraph` and `network`. ... and there were upcoming `igraph` changes (1.0.0). But it is indeed worth implementing.

**Comment by briatte** [comment]
Thanks for the explanation(s).

**Pull request merged**
