### PR TITLE
Ggcorr legend

### PR DESCRIPTION
**Pull request by elbamos**
This is another attempt to make a pull request for the changes to ggcorr.  Basically, it allows the user to set the number of breaks in the legend, fixes the scale used in the legend, and has an option to use the Greek letter Rho (in LaTeX) as the legend title.

### CODE REVIEW

**Comment by schloerke** [comment]
Looks good!  I look at it soon.

(For future requests, can you pull-request to the dev branch?  Thank you.)

Thank you
- Barret

**Comment by elbamos** [comment]
I will try - I’m learning!  Your directions helped a lot.

**Comment by elbamos** [comment]
Would you mind taking a peek at ggnetworkmap?  https://github.com/elbamos/ggally/tree/ggnetworkmap/R   I fixed what seemed to not be working in ggnet, and I added great circles.  But somewhere along the way, the direction of arrowheads seems to have broken.  This may be a ggplot issue, but after two hours of staring at it…  Anyway, if someone who knows arrows doesn’t see a solution quickly, I think i’ll just kill them and do the pull request without arrows, since I don’t need them.

**Comment by schloerke** [comment]
Can you give me some basic examples that show off ``ggnetworkmap`` and also show where the arrow functionality breaks?

**Comment by elbamos** [comment]
There's a shortage of pre-built geographic network data for making minimal examples, but how's this:

airports <- read.csv("http://datasets.flowingdata.com/tuts/maparcs/airports.csv", header=TRUE)
airports$lon <- airports$long

flights <- data.frame(origin = sample(airports$iata, 500, replace = TRUE), 
	destination = sample(airports$iata, 500, replace = TRUE))
graph <- igraph::graph.data.frame(flights, airports, directed = TRUE)
us <- ggmap::ggmap(ggmap = get_map(location = "United States", 3, color = "bw"))

# An example of what it does...

us %>% ggnetworkmap(graph, size = 1, great.circles = TRUE, node.color = "orange",
		segment.color = "cornflowerblue", weight.method = "none") + 
                 xlim(-125,-60) + ylim(30, 45)

#  And the broken arrows...

us %>% ggnetworkmap(graph, size = 2, arrow.size = 0.3, great.circles = TRUE, node.color = "orange",
		segment.color = "cornflowerblue", weight.method = "none") + xlim(-80, -70) + ylim(40, 45)

**Comment by schloerke** [comment]
Broken arrows! I believe we have found an issue with ggmap (or something).

I have removed the magrittr depends in the code below

Example from above:
```{r}
ggnetworkmap(us, graph, size = 2, arrow.size = 0.3, great.circles = TRUE, node.color = "orange", segment.color = "cornflowerblue", weight.method = "none") + xlim(-107,-90) + ylim(25,35)
```
screen shot 2015-01-04 at 3 28 38 pm

I'm guessing you were looking for something like this:
```{r}
ggnetworkmap(us, graph, size = 2, arrow.size = 0.3, great.circles = TRUE, node.color = "orange", segment.color = "cornflowerblue", weight.method = "none") + coord_cartesian(xlim = c(-107,-90), ylim = c(25,35))
```
screen shot 2015-01-04 at 3 29 31 pm

Take a look at examples 2 and 3 here: http://docs.ggplot2.org/current/coord_cartesian.html



The odd zooming behavior is not an issue of your code.
```{r}
us + xlim(-107,-90) + ylim(25,35)
```
screen shot 2015-01-04 at 3 31 26 pm

```{r}
us + coord_cartesian(xlim = c(-107,-90), ylim = c(25,35))
```
screen shot 2015-01-04 at 3 32 07 pm

The two pictures should be the same.

**Comment by elbamos** [comment]
So you're saying it works?  Yay! What do you think so far?  I'm revising it a bit to try to see if I can get edge coloration and two-toned points working, and more NSE.

**Comment by schloerke** [comment]
I have made some changes / updates to the code:

Can you pull in those changes?  This should work (not tested)
```{bash}
git fetch upstream # upstream points to ggobi repo
git checkout ggnetworkmap
git merge upstream/elbamos_ggnetworkmap
```

Can you add parameter descriptions to ``layout.par`` and ``names``, please?
```
* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'ggnetworkmap'
  ‘layout.par’ ‘names’
```

**Comment by elbamos** [comment]
I rewrote most of the function to use more non-standard evaluation.  It will also generate a Fruchterman-Reingold layout if it is not passed a ggplot object.  Instead of passing vectors or whatever to specify weight and node group membership, the user passes the unquoted name of a vertex attribute.  This makes it consistent with ggplot (I've got most of how to build a geom figured out, I think, but not quite all).  It also allows nodes to be members of two groups, in which case the points are plotted with a ring.

This is intended for comparing some network statistic (community membership, betweenness, etc.) to some non-network statistic.   

I wanted to get edge-groupings and colors in as well, but I can't figure out how to give ggplot more than two color scales.  This may be a fixed ggplot limitation.  

I have tried to put in all of your changes; if I missed any, I apologize - I had already done a lot of the re-writing when I got your notice so I couldn't easily run a diff.  

I have not made docs for it, or tried to update the pull request.  The reason is, there is now a great deal of functionality, and I'm not sure there's full code coverage yet.  I've put it through some trials and haven't broken it.  I'd appreciate if you could take a pass as well.  I'm going to take the airplane example and try to demonstrate some of the new functionality with it.  

What do you think?

**Comment by elbamos** [comment]
ggnetworkmap should be good now... I'm going to see if I can figure out how to comment there...

**Comment by schloerke** [comment]
Couple questions

* The ``nbreaks`` looks great
* For latexify, why not use the ``name`` argument?
```{r}
nba <- read.csv("http://datasets.flowingdata.com/ppg2008.csv")
ggcorr(nba[, -1], name = "$\\rho$")
```
Can also be used to use ```expression```
```{r}
ggcorr(nba[, -1], name = expression(rho))
```
screen shot 2015-01-14 at 12 23 00 pm


* The changes made in ``geom=="circle"``, what was the motivation for using ``scale_size_continuous`` rather than ``scale_size_area``?  The small circles produces with ``scale_size_continuous`` seem to be too small.  Strong negative correlation values are being displayed as small values.  Is it possible to have large circles for corr values near -1 and 1, but small near 0?

**Comment by elbamos** [comment]
You're right about "name." Regarding the circle sizes, with the original code where there isn't a large range of correlations there was effectively no visual distinction in the presentation of circle sizes, and they tended to overflow their spots.  You have a good point regarding getting the size to shrink at zero and rise with negative correlations. I'm not sure if it's possible - it may mess-up the legend - but I'll give it a try tonight. My recollection about changing size scales is that it may have been necessary to get ggplot2 to put size and color in a single legend, but it was a few weeks ago so that may be wrong.

**Comment by schloerke** [comment]
How about this?  It doesn't show the size change, but that info doubled with color. While it is doubled in displaying the info, it makes it **very** quick to see what's going on.

screen shot 2015-01-14 at 12 46 05 pm

**Comment by elbamos** [comment]
I actually find this a lot harder to read.  I think it may be because the small dots just don't show up, or because there aren't enough breaks for my eyes to figure out what the size is doing.

**Comment by schloerke** [comment]
What about a min_size argument?

This example has a min size of 3 and max size of 6.

screen shot 2015-01-14 at 3 43 41 pm

**Pull request closed without merging**
