### PR TITLE
Reverse Y axis in `ggally_count()`

### PR DESCRIPTION
**Pull request by schloerke**
Fixes https://github.com/ggobi/ggally/issues/386

### CODE REVIEW

**Comment by schloerke** [comment]
@Generalized Can you try this branch? 

```r
remotes::install_github("ggobi/ggally#420")
```

**Comment by Generalized** [comment]
Dear @schloerke 
I just installed this branch, but the result seems to be the same:

It is:
obraz


while it should be:

obraz

**Comment by schloerke** [comment]
@Generalized May I have the code you are using to produce both plots?

**Comment by schloerke** [comment]
> EDIT: I'm sorry, after restaring the RStudio - it works now! Thank you!

Yay! Glad it works now

**Pull request merged**
