### PR TITLE
ggcoef

### PR DESCRIPTION
**Pull request by larmarange**
cf. https://github.com/ggobi/ggally/issues/160

### CODE REVIEW

**Comment by schloerke** [comment]
Can you run ``devtools::document()``, please?

This should get it to pass ``devtools::check()`` / travis

**Comment by larmarange** [comment]
I have fixed warnings and notes from `devtools::check()`.

However, Travis failed with examples from `ggparcoord`. Any idea?

**Comment by schloerke** [comment]
Since the issues are not from your code, I'll take it from here. :-)

Thank you for the updates!

- Barret

**Comment by schloerke** [comment]
http://ggobi.github.io/ggally/gh-pages/ggcoef.html

This is up now. Merged in with dev.  I'll uncomment on the gh-pages index page once it moves to master. (This might be a couple months. I plan on doing a release before end of June)

Thanks again for the function!

Side note on ggparcoord.  ggplot2 updated the diamonds data to be a tbl_df and a data.frame.  So most of the functions were just fine.  However, ```diamonds[,"color"]``` is not the same as ```as.data.frame(diamonds)[, "color"]```.  The first returns a data.frame with a single column.  The second returns a vector.  I was expecting a vector and not a data.frame.   

... now we know. lol

**Comment by larmarange** [comment]
Thanks.

With `data.table` and `dplyr` it's becoming better to use `[[]]` syntax for column extracting.

Regards

**Pull request merged**
