### PR TITLE
100% coverage for ggnet, very first version of ggnet2

### PR DESCRIPTION
**Pull request by briatte**
- 100% coverage for `ggnet`.
- Very first version of `ggnet2`.

### CODE REVIEW

**Comment by briatte** [comment]
Very first version of `ggnet2`.

**Comment by briatte** [comment]
Thanks for the merge.

I have one more pull request coming, today, with some further improvements to `ggnet2`.

I'm also going to remove the `cityServiceFirms` dataset from the package: it's not essential to illustrate anything particular, and I could not find any piece of code that relies on it.

**Comment by schloerke** [comment]
Can you make an issue for the dataset removal, instead? Since this will be
a major upgrade, I think it'll be ok. I just want to be sure.

Sounds good on ggnet2. I'll be merging in some Travis changes this
afternoon.

**Comment by briatte** [comment]
Newbie question: is there any way I can lose the compulsory dependency to `intergraph` in my code?

So far I have it listed as "required" as follows:

```{r}
require_pkgs(c("intergraph", "network", "RColorBrewer", "sna"))
```

Is it okay to remove it from there and have instead, at the only point of the code where it is used:

```{r}
if (class(net) == "igraph" & require(intergraph, quietly = TRUE)) {
  net = intergraph::asNetwork(net)
} else if (class("net") == "igraph") {
  stop("install the 'intergraph' package to use igraph objects with ggnet2")
}
```

I suspect this will raise a warning in `R CMD CHECK`.

**Comment by briatte** [comment]
Question: is it okay to have this kind of code to avoid making the function dependent on the `intergraph` package?

```{r}
  if (class(net) == "igraph" && "intergraph" %in% rownames(installed.packages())) {
    net = intergraph::asNetwork(net)
  } else if (class("net") == "igraph") {
    stop("install the 'intergraph' package to use igraph objects with ggnet2")
  }
```

This seems to pass `R CMD CHECK`, but will it include the `intergraph` package in the `Suggests`?

I'm thinking of using this both for `intergraph` and `RColorBrewer`, in order to make `ggnet2` dependent only on these:

```{r}
require(network      , quietly = TRUE) # network objects
require(sna          , quietly = TRUE) # placement and centrality

require(ggplot2      , quietly = TRUE) # grammar of graphics
require(grid         , quietly = TRUE) # arrows
require(scales       , quietly = TRUE) # sizing
```

Now, as far as I understand, `ggplot2` and `grid` are in the `Imports`, so I can skip these, and just need to require `network`, `sna` and `scales`.

**Comment by schloerke** [comment]
Yes, this allows for a suggested package.  To me, a suggested package is something that could be used, but isn't necessary for the package/function to work.  In the ggnet code, we are covering our based by only using it in a "you gave me an X object, I'm going to make sure you have X's package.  If you don't, stop()".  We are not going against the idea of different code paths stated in https://cran.r-project.org/doc/manuals/R-exts.html#Suggested-packages as it function stops executing and issues an error if the odd situation occurs.

```intergraph``` will need to be in the Suggestions, if the function could possibly use a function in the ```intergraph``` package but isn't necessary for ggnet to work.  

Correct.  You will only need to require ```network```, ```sna```, and ```scales``` in the ```ggnet2``` function.  Since they are Suggested packages, you'll need to use the ``::`` function calls. (Which you've already done).

**Comment by briatte** [comment]
Perfect, thanks!

**Pull request merged**
