### PR TITLE
Fix visual glitch when overlaying network on world map

### PR DESCRIPTION
**Pull request by elbamos**
`ggnetworkmap` was producing gltichy lines if certain maps were used underneath, under certain conditions.  Thanks to Marten Winter for nagging me to fix this.

### CODE REVIEW

**Comment by MartenWinter** [comment]
Heja Amos,

it works! Thanks a lot!!!!

**Comment by MartenWinter** [comment]
If I use coord_map(ylim...) element to cut of the Antarctica it again produces the lines?

**Comment by schloerke** [comment]
Do either of you have a code example? (for my learning purposes)

**Comment by schloerke** [comment]
moved to #157 to point to dev

**Comment by schloerke** [comment]
on cran (version 1.1.0)

**Pull request closed without merging**
