### PR TITLE
added parameter for size of censoring points

### PR DESCRIPTION
**Pull request by EdwinTh**
I added a parameter for the size of censoring. I also planned to add parameters for the size of estimate and CI but I found out you already had been taking care of it ;)

### CODE REVIEW

**Comment by schloerke** [comment]
Hi Edwin,

Couple things... Could you:
* Run ``devtools::document()`` (Helps travis pass)
* Fix the test failures in tests/testthat/test-ggsurv.R
```{r}
tf <- function(file = "gg-plots", package = "./") {
  devtools::load_all(package)
  testthat::test_file(file.path(package, "tests", "testthat", paste0("test-", file, ".R")))
}
tf("ggsurv")
```

These changes should have it pass devtools::check().

Thank you,
Barret

**Comment by schloerke** [comment]
oh! If possible, could you resubmit the PR to the dev branch of ggobi/ggally? Thank you!

Something weird is happening with the file diff'ing.  I can't see what's changed.  It basically shows a new file vs an old file.  Don't know how to fix that one, but hopefully a new submission helps.

**Comment by EdwinTh** [comment]
Sure will look into it soon. Thanks Barrett.

**Comment by schloerke** [comment]
closed in #176

**Pull request closed without merging**
