### PR TITLE
Ggnetworkmap

### PR DESCRIPTION
**Pull request by elbamos**
This is a pull request for the ggnetworkmap() function.  It started as a modification of ggnet that was originally intended to resolve the limitation that ggnet cannot be plotted over maps.  It evolved to allow setting multiple groups/color schemes for nodes, supporting non-standard evaluation (not quite ggplot2, but getting there), offering plotting with great circles, and a few other things.  I'd like to allow setting groups for segments as well, but I haven't figured out how to get ggplot2 to allow three color schemes on the same plot.  

Please note that I've tried to put this through its paces (it was written to deal with some complex data), but this is a function that has a lot of functionality inherited from ggnet, and code coverage is hard to guarantee.

### CODE REVIEW

**Comment by schloerke** [comment]
Do you still have the test code?

Can you run this code:
```{r}
devtools::use_testthat()
```

Then add a file named ``./tests/testthat/ggnetworkmap.R`` with all of the tests?  You can see an example in "Test structure" of http://r-pkgs.had.co.nz/tests.html. 

Thank you for the extra work!  It'll make sure all functionality is never lost and is displayed.

p.s. still have continuation exams this week, will get to the code next week.

**Comment by schloerke** [comment]
using this package: https://github.com/hadley/testthat

**Comment by elbamos** [comment]
Ok - I did that.  Thanks for helping me along with all of this.

**Comment by elbamos** [comment]
I checked, and its failing on the import of ggmap::.  That's only necessary for the example and the tests, not for the working code.  What to do?

**Comment by schloerke** [comment]
It should be in the package suggests. Also, you will need to require it
when doing examples. Suggested packages are not loaded automatically.

Should be similar to this commit:
https://github.com/ggobi/ggally/commit/a492ceb62d4bd3b414ca3305b311a55c5863693c

**Comment by elbamos** [comment]
I put it in a library clause, but Travis is saying it cannot find the package.

**Comment by elbamos** [comment]
Ah ok I get it-will take care of it tonight.

**Comment by elbamos** [comment]
I'm still getting the same build error...  Any suggestions?

**Comment by schloerke** [comment]
I made some changes here: https://github.com/ggobi/ggally/compare/2660980...elbamos_ggnetworkmap2

To quickly run your tests without doing a full package ``check()``, I do:
```{r}
# library(testthat)
load_all("./")
test_package("GGally")
```
This way you can get the traceback, full print output, and get the warnings.

I'm having errors with the code above.  There are no errors being reported, but there are errors if I run them manually.  ...weird.  Maybe it's in the setup of the testing? idk


Other than the testing 1 thing left:
```
* checking R code for possible problems ... NOTE
ggnetworkmap: no visible binding for global variable ‘.label’
```

**Comment by elbamos** [comment]
When I run that, I get a bunch of errors which are that test functions did NOT return an error.  I think what happened here is I don’t know how to use testthat.  I intended for it to run various plots and fail if any of the plots errored.  Its doing the opposite — testthat is failing when an error when a plot *doesn’t* error.  

I saw that .label thing too, I’m not sure what it is; only comes up in the testing, and just as a warning.

**Comment by elbamos** [comment]
Just to be clear -- I can't figure out how to reverse the testthat thing so it fails on error instead of failing when there *isn't* an error.  It must be something obvious because its the most obvious thing, but...

**Comment by elbamos** [comment]
Ah - figured out .label.  It happens because of the non-standard evaluation.  It isn't an error or a problem.

**Comment by elbamos** [comment]
This didn't get posted for some reason, but its the reason for the test failures:  

When I run that, I get a bunch of errors which are that test functions did NOT return an error.  I don’t know how to use testthat.  I intended for it to run various plots and fail if any of the plots errored.  Its doing the opposite — testthat is failing when an error when a plot *doesn’t* error.   Can you help?

**Comment by elbamos** [comment]
Wow!  After all that, finally it clears.  Ok - let's go?

**Comment by elbamos** [comment]
Buddy?

**Comment by schloerke** [comment]
Quals have finished up and school just started up again.  Now I'm back.

Final touch:  Can you add a description about the twitter data?  Create a file similar to "./R/data-*.r" in the repo.

**Comment by elbamos** [comment]
I did write the file and push it -- i'm not sure how to do that now that the branch is merged?  Thanks!

**Pull request closed without merging**
