### PR TITLE
pass "crosstalk key" to ggplot_build(), but dont plot it

### PR DESCRIPTION
**Pull request by cpsievert**

### CODE REVIEW

**Comment by schloerke** [comment]
Hey Carson. What's the goal of the crosstalk column?  

Where can it enter the code and where is it needed?

**Comment by cpsievert** [comment]
That column provides the link necessary to do linked brushing. I'm pretty sure before you're recent changes it was being passed along to the build step without `ggpairs()` trying to plot it, but now it looks like it tries to plot that extra column by default (which should never happen).

**Comment by cpsievert** [comment]
Here's an example:

```r
sd <- crosstalk::SharedData$new(iris[1:4])
ggpairs(sd) 
plotly::ggplotly()
```

**Comment by cpsievert** [comment]
The `fortify()` introduced in #186 is where we initially added support (which is where the new column is added)

**Comment by schloerke** [comment]
Thanks for the example! I'll take a look tomorrow.

Once I can download the updated ggplot2 from cran, I'll release.

- Barret

**Comment by schloerke** [comment]
I'm having trouble with this.

The `sd` object is a SharedData, R6 classed object.  It has the method `data(withKey = TRUE)`, but I can't seem to find a ".crossTalkKey" in the output.

```
> sd
<SharedData>
  Public:
    .updateSelection: function (value) 
    clearSelection: function (ownerId = "") 
    clone: function (deep = FALSE) 
    data: function (withSelection = FALSE, withFilter = TRUE, withKey = FALSE) 
    groupName: function () 
    initialize: function (data, key = NULL, group = createUniqueId(4, prefix = "SharedData")) 
    key: function () 
    origData: function () 
    selection: function (value, ownerId = "") 
    transform: function (func) 
  Private:
    .data: data.frame
    .filterCV: ClientValue, R6
    .group: SharedData52060072
    .key: NULL
    .rv: reactivevalues
    .selectionCV: ClientValue, R6
```

Also, `ggplot2::fortify(sd)` doesn't like the `sd` object.

```
> ggplot2::fortify(sd)
Error: ggplot2 doesn't know how to deal with data of class SharedData/R6
```

```
> devtools::session_info()
Session info ------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, darwin13.4.0        
 ui       X11                         
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Indiana/Indianapolis
 date     2016-11-06                  

Packages ----------------------------------------------------------------------
 package      * version     date       source                            
 assertthat     0.1         2013-12-06 CRAN (R 3.1.2)                    
 base64enc      0.1-3       2015-07-28 CRAN (R 3.2.2)                    
 colorout     * 1.1-2       2016-07-19 Github (jalvesaq/colorout@6d84420)
 colorspace     1.2-7       2016-10-11 cran (@1.2-7)                     
 crayon         1.3.2       2016-06-28 cran (@1.3.2)                     
 crosstalk      0.2         2016-07-30 Github (rstudio/crosstalk@209ac2a)
 curl           2.1         2016-09-22 cran (@2.1)                       
 DBI            0.5-1       2016-09-10 cran (@0.5-1)                     
 devtools     * 1.12.0.9000 2016-11-03 Github (hadley/devtools@b6e40ae)  
 digest         0.6.10      2016-08-02 cran (@0.6.10)                    
 dplyr          0.5.0       2016-06-24 cran (@0.5.0)                     
 GGally       * 1.2.9.9999  <NA>       local                             
 ggplot2        2.1.0.9001  2016-11-03 Github (hadley/ggplot2@9869339)   
 git2r          0.15.0      2016-05-11 cran (@0.15.0)                    
 gtable         0.2.0       2016-02-26 CRAN (R 3.2.3)                    
 htmltools      0.3.5       2016-03-21 CRAN (R 3.2.3)                    
 htmlwidgets    0.7         2016-08-02 cran (@0.7)                       
 httpuv         1.3.3       2015-08-04 CRAN (R 3.2.0)                    
 httr           1.2.1       2016-07-03 cran (@1.2.1)                     
 jsonlite       1.1         2016-09-14 cran (@1.1)                       
 lazyeval       0.2.0.9000  2016-09-30 Github (hadley/lazyeval@c155c3d)  
 magrittr       1.5         2014-11-22 CRAN (R 3.1.2)                    
 memoise        1.0.0       2016-01-29 CRAN (R 3.2.3)                    
 mime           0.5         2016-07-07 cran (@0.5)                       
 munsell        0.4.3       2016-02-13 CRAN (R 3.2.3)                    
 plotly         4.5.5.9000  2016-10-19 Github (ropensci/plotly@5fcdaa7)  
 plyr           1.8.4       2016-06-08 CRAN (R 3.3.0)                    
 prettyunits    1.0.2       2015-07-13 CRAN (R 3.3.1)                    
 progress       1.0.2       2015-06-05 CRAN (R 3.3.1)                    
 purrr          0.2.2.9000  2016-09-30 Github (hadley/purrr@8c72c35)     
 R6             2.2.0       2016-10-05 CRAN (R 3.3.1)                    
 RColorBrewer   1.1-2       2014-12-07 CRAN (R 3.2.0)                    
 Rcpp           0.12.7      2016-09-05 cran (@0.12.7)                    
 reshape        0.8.6       2016-10-21 cran (@0.8.6)                     
 roxygen2       5.0.1       2015-11-11 CRAN (R 3.2.2)                    
 rstudioapi     0.6         2016-06-27 CRAN (R 3.3.1)                    
 scales         0.4.0.9003  2016-10-16 Github (hadley/scales@d58d83a)    
 shiny          0.14.1      2016-10-05 cran (@0.14.1)                    
 stringi        1.1.2       2016-10-01 cran (@1.1.2)                     
 stringr        1.1.0.9000  2016-11-02 Github (hadley/stringr@c31c914)   
 testthat       1.0.2.9000  2016-07-20 Github (hadley/testthat@46d15da)  
 tibble         1.2         2016-08-26 cran (@1.2)                       
 tidyr          0.6.0.9000  2016-09-30 Github (hadley/tidyr@3c9335b)     
 viridisLite    0.1.3       2016-03-12 cran (@0.1.3)                     
 withr          1.0.2       2016-06-20 CRAN (R 3.3.0)                    
 xtable         1.8-2       2016-02-05 CRAN (R 3.2.3)        
```

**Comment by cpsievert** [comment]
At least for now, [`fortify.SharedData()` is defined in plotly](https://github.com/jcheng5/plotly/blob/joe/feature/crosstalk/R/plotly_data.R#L237-L245), so you'll need to load it .

**Comment by schloerke** [comment]
Think it would be ok to just copy that function? Doing the whole circular
depends is no fun.

**Comment by cpsievert** [comment]
Fine with me!

**Pull request merged**
