### PR TITLE
Improvements and bug fixes for ggally_colbar(), ggally_rowbar() and ggbivariate()

### LINKED ISSUE #374: change the order of levels in ggally_rowbar()
See this example:

```r
data(tips, package = "reshape")
ggbivariate(tips, outcome = "smoker", explanatory = c("day", "time", "sex", "tip"))
```

image

While for boxplot() the order of values is no/yes, for the row bars, the order is yes/no.

`ggally_rowbar()` should be updated (eventually with an option) to reverse the order of values.

To be noted, it is not a problem with `ggally_colbar`:

```r
ggduo(tips, columnsX = c("tip", "day"), columnsY = "smoker", types = list(discrete = "colbar", combo = "box"), legend = 2)
```

image

### LINKED ISSUE #376: Consider adding frequency label as an option in ggbivariate?
Hi, I really like ggbivariate. As an option, could the function allow users to display the frequency instead of the percentage? This is useful where there are low numbers in categories and the percentage could be misleading. Example below of using ggbivariate then the same plot but with frequency labels instead of percentage.

library(tidyverse)
library(GGally)

# GGally ggbivariate
mtcars %>% 
  dplyr::mutate_all(as.factor) %>% 
  GGally::ggbivariate(outcome = "vs", explanatory = "gear")

# GGally with bivariate with frequency label option?
mtcars %>% 
  dplyr::group_by(gear,vs) %>% 
  dplyr::summarise(n = dplyr::n()) %>% 
  dplyr::mutate(vs = as.factor(vs)) %>% 
  ggplot2::ggplot() +
  ggplot2::aes(x = gear,
               y = n,
               fill = vs,
               label = n) +
  ggplot2::geom_bar(position="fill", 
                    stat="identity") +
  ggplot2::geom_text(size = 3, 
                     position = position_fill(vjust = 0.5),
                     colour = "black") +
  ggplot2::coord_flip() +
  ggplot2::scale_y_continuous(labels = scales::percent)

### LINKED ISSUE #390: Allowing rmarkdown in Roxygen
Would you consider to change `Roxygen: list(markdown = FALSE)` by `Roxygen: list(markdown = TRUE)` in DESCRIPTION?

It would be much easier to write documentation and ensure that internal and external links are accurate with the last versions of R. (cf. https://github.com/r-lib/roxygen2/issues/1108 )

### PR DESCRIPTION
**Pull request by larmarange**
Fixes #374
Fixes #390
Fixes #376

- Fix #374 using a new arguments reverse_fill_labels
- bug fix regarding remove_percentage_axis in ggally_rowbar()
- if background is removed, axis should not be expanded
- better default values for ggbivarite()

### CODE REVIEW

**Comment by larmarange** [comment]
cf. #376 as well

**Comment by larmarange** [comment]
Hi, just for a quick update. Is there any issue with this PR?

**Comment by larmarange** [comment]
Note: R-CMD check for windows (devel) is due to the fact that the binaries of the last version of igraph are not yet available for windows devel. cf. https://cran.r-project.org/package=igraph

**Comment by larmarange** [comment]
tests failing in the current master branch have also been fixed in this PR (cf. https://github.com/ggobi/ggally/pull/375/commits/2ea0f4b2d4421a3056675e708a5295c30db833b8)

**Comment by schloerke** [comment]
@larmarange Wow! Amazing changes.  Please let me know when this PR is ready to merge.

Request: Add a "breaking changes" news entry that some `ggtable(cells, fill)` values have changed

**Comment by larmarange** [comment]
NEWS has been updated accordingly

**Comment by larmarange** [comment]
I have also added the support of markdwon in documentation (cf. #390 ).

The PR should be complete.

PS: I'm currentky working on the redesign of ggcoef ( #372 ) and hope to be able to send a PR soon

**Comment by larmarange** [comment]
Dear @schloerke 

just to inform you that the PR is ready for merging and now pass all checks.

It will fix several issues (#374  #390 and #376) as well as some CRAN checks in master branch.

**Comment by larmarange** [comment]
Dear @schloerke 

is there any reason blocking the integration of this PR? It will solve the current check problems in master and fix several bugs

**Comment by schloerke** [comment]
@larmarange Thank you for your patience. I am swamped at work 😞. Merging now.

**Comment by larmarange** [comment]
Thank you very much

**Pull request merged**
