### PR TITLE
use withr to manage local tempfile

### PR DESCRIPTION
**Pull request by MichaelChirico**

### CODE REVIEW

**Comment by schloerke** [comment]
@MichaelChirico This is a perfect code change, but it would require a new dependency on `{withr}`. `{ggally}` already has a fair amount of dependencies, so I'd like to reject this PR as to not add `{withr}` for a single change.  

Thank you! Sorry we couldn't accept the PR this time

**Comment by MichaelChirico** [comment]
Hi @schloerke you already depend on withr! since testthat imports it. this change doesn't affect your dependency graph at all :)

**Comment by schloerke** [comment]
Correct, but how many stated dependencies in the DESCRIPTION file is what matters.  While it doesn't install anything new, it would create a new `Suggests` or `Imports` dependency. I'd like to keep them minimal when possible. 

CRAN produces warnings around 15 or 17 packages, I can't remember.

**Comment by MichaelChirico** [comment]
AFAIK, that's not true.

That rule _applies to Imports_, not Suggests:

https://cran.r-project.org/doc/manuals/r-release/R-ints.html (look for `_R_CHECK_EXCESSIVE_IMPORTS_` -- the limit is 20, _for imports_)

In fact, the error message you get for too many imports _suggests you move packages to Suggest_:

https://github.com/r-devel/r-svn/blob/master/src/library/tools/R/QC.R

(search for `x$many_imports`, sorry, the very large file doesn't allow me to link directly)

`testthat` is already in your Suggests:

https://github.com/ggobi/ggally/blob/53c1f656448648942d86bcbc1b82059c09f47029/DESCRIPTION#L67

And this change would put `withr` into your Suggests.

I don't see any problem at all with adding `withr`, even from a CRAN submission point of view.

**Pull request closed without merging**
