### PR TITLE
A new stat allowing to compute weighted mean and a ggally_trends()

### PR DESCRIPTION
**Pull request by larmarange**

### CODE REVIEW

**Comment by larmarange** [comment]
Following a need that I had on different projects, I propose a new stat `stat_weighted_mean()` allowing to compute properly weighted means (or proportions) directly in `ggplot2` for easy trends graph.

The PR also includes a `ggally_trends()` type of plots, using this new stat, and working with both continuous and discrete variables.

**Comment by schloerke** [comment]
Do you mind adding a news item to this PR (and other PRs)?  

There are a lot of good things going on and I want to make sure people know about them.

**Comment by larmarange** [comment]
No problem, will do

**Comment by larmarange** [comment]
Just one thing: with several PR adding elements to `NEWS.md`, it will result in conflicts when merging all the PR.

Do you prefer that I add now elements to NEWS.md and you will solve the conflicts or do you prefer to merge the different PR and then I will propose an additionnal PR documenting all the new plots and stats in NEWS.md ?

**Comment by larmarange** [comment]
Regarding this PR and other PR, 3 new stat have been proposed. Each of them would benefit from a dedicated vignette. However, I'm waiting that you switch to `pkgdown` to propose these vignettes.

Similarly, some global functions as `ggcross()`, `ggtable()` or `ggtrends()` that will use the new basic plots with `ggduo()` will propose later, once all PR merged.

**Comment by schloerke** [comment]
>I will propose an additionnal PR documenting all the new plots and stats in NEWS.md 

Let's do this "global news update" PR.  That'll make the conflicts easier to manage and easier to see all at once. 😄 


> However, I'm waiting that you switch to pkgdown to propose these vignettes

I will work on this tonight. Feel free to have them ready to drop in.  I'm going to convert our existing items by copy/pasting into separate files.

Thank you so much!

**Pull request merged**
