### PR TITLE
v2.1.0

### PR DESCRIPTION
**Pull request by schloerke**
- [x] Add news entry for `ggcoef` and friends
- [x] bump version
- [x] Pass all GHA checks
- [x] Fix [`GGally` CRAN errors](https://cloud.r-project.org//web/checks/check_results_GGally.html)
- `devtools::check_win_devel()`, `devtools::check_win_release()`, `devtools::check_win_oldrelease()`
  * [x] submit 
  * [x] pass
- [x] `revdepcheck::revdep_check()`
  * 112!
  - [x] bootcluster has an import conflict with `GGally::%>%` and `sets::%>%`. Must wait until Dec 29th to submit to CRAN
- [x] Update cran comments
- [x] `devtools::release()`
- [x] CRAN accepts `GGally`

cc @larmarange

### CODE REVIEW

**Comment by larmarange** [comment]
Thanks @schloerke

**Comment by schloerke** [comment]
@larmarange We are just waiting on the "allow 2 weeks for maintainers to update their packages" with `bootcluster`. I cc'd you in the email, but your email address was rejected.  If I hear from the `bootcluster` maintainer sooner and they post to CRAN, I'll submit `GGally` earlier.

`GGally` is ready to go! Just need to hit the correct buttons for `devtools::release(check = TRUE)` on the 29th. 🥳

**Comment by schloerke** [comment]
Submitted to CRAN. 🤞 

There's a backlog with CRAN returning from vacation today.

**Comment by schloerke** [comment]
Accepted by cran. 🎊
Will merge the PR tomorrow

**Comment by larmarange** [comment]
That's great!!!!

**Pull request merged**
